#****************************************************************************
#* envrc_sections.py
#*
#* Copyright 2024 Matthew Ballance and Contributors
#*
#* Licensed under the Apache License, Version 2.0 (the "License"); you may
#* not use this file except in compliance with the License.
#* You may obtain a copy of the License at:
#*
#*   http://www.apache.org/licenses/LICENSE-2.0
#*
#* Unless required by applicable law or agreed to in writing, software
#* distributed under the License is distributed on an "AS IS" BASIS,
#* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#* See the License for the specific language governing permissions and
#* limitations under the License.
#*
#****************************************************************************
"""Sentinel-wrapped sections inside ``packages/packages.envrc``.

The direnv handler (ENVIRONMENT phase) writes the base file on every update.
Handlers that contribute activation state of their own (modules, python,
node, fusesoc) insert a section bracketed by begin/end sentinel comments so
it can be replaced or removed on later runs.
"""
import logging
import os

_logger = logging.getLogger("ivpm.handlers.envrc_sections")

PACKAGES_ENVRC = "packages.envrc"
ENVRC_HEADER = "# Generated by IVPM — do not edit manually\n"


def _find_section(content: str, begin: str, end: str):
    """Return the (start, stop) span of the begin..end section, or None."""
    begin_idx = content.find(begin)
    end_idx = content.find(end)
    if begin_idx == -1 or end_idx == -1:
        return None
    stop = content.find("\n", end_idx)
    stop = len(content) if stop == -1 else stop + 1
    return begin_idx, stop


def patch_envrc_section(deps_dir: str, begin: str, end: str, body: str):
    """Insert or replace the ``begin``..``end`` section of packages.envrc.

    ``body`` is the text between the sentinels (newline-terminated). The file
    is created with just the header if it does not exist yet, so a section is
    never silently dropped.
    """
    envrc_path = os.path.join(deps_dir, PACKAGES_ENVRC)
    section = "%s\n%s%s\n" % (begin, body, end)

    if os.path.isfile(envrc_path):
        with open(envrc_path) as fp:
            content = fp.read()
    else:
        content = ENVRC_HEADER

    span = _find_section(content, begin, end)
    if span is not None:
        new_content = content[:span[0]] + section + content[span[1]:]
    else:
        if begin in content or end in content:
            _logger.warning(
                "%s has incomplete '%s' sentinels; appending new section",
                PACKAGES_ENVRC, begin)
        new_content = content + "\n" + section

    with open(envrc_path, "w") as fp:
        fp.write(new_content)


def remove_envrc_section(deps_dir: str, begin: str, end: str):
    """Remove the ``begin``..``end`` section from packages.envrc, if present."""
    envrc_path = os.path.join(deps_dir, PACKAGES_ENVRC)
    if not os.path.isfile(envrc_path):
        return
    with open(envrc_path) as fp:
        content = fp.read()
    span = _find_section(content, begin, end)
    if span is None:
        return
    start, stop = span
    # Drop the blank line patch_envrc_section put in front of the section.
    if content[max(0, start - 2):start] == "\n\n":
        start -= 1
    with open(envrc_path, "w") as fp:
        fp.write(content[:start] + content[stop:])
