#****************************************************************************
#* package_handler_fusesoc.py
#*
#* Copyright 2024 Matthew Ballance and Contributors
#*
#* Licensed under the Apache License, Version 2.0 (the "License"); you may
#* not use this file except in compliance with the License.
#* You may obtain a copy of the License at:
#*
#*   http://www.apache.org/licenses/LICENSE-2.0
#*
#* Unless required by applicable law or agreed to in writing, software
#* distributed under the License is distributed on an "AS IS" BASIS,
#* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#* See the License for the specific language governing permissions and
#* limitations under the License.
#*
#****************************************************************************
import configparser
import dataclasses as dc
import glob as _glob
import logging
import os
from typing import Dict, List, Optional

from ..package import Package
from ..project_ops_info import ProjectUpdateInfo
from .package_handler import PackageHandler

_logger = logging.getLogger("ivpm.handlers.package_handler_fusesoc")

# Sentinel markers for the fusesoc section inside packages/packages.envrc
_SENTINEL_BEGIN = "# --- ivpm:fusesoc begin ---"
_SENTINEL_END   = "# --- ivpm:fusesoc end ---"
_FUSESOC_CONF_PREFIX = "library.ivpm."


def _has_cores_nonrecursive(path: str) -> bool:
    """Return True if *path* contains at least one valid FuseSoC ``.core`` file.

    Only the immediate directory is scanned (non-recursive).  Each ``*.core``
    file is checked for the ``CAPI=2`` marker so that non-FuseSoC ``*.core``
    files (core dumps, etc.) are not mistaken for core descriptions.
    """
    if not os.path.isdir(path):
        return False
    try:
        entries = os.listdir(path)
    except OSError:
        return False
    for name in entries:
        if not name.endswith(".core"):
            continue
        core_path = os.path.join(path, name)
        if not os.path.isfile(core_path):
            continue
        try:
            with open(core_path, "rb") as fh:
                head = fh.read(4096)
            if b"CAPI=2" in head:
                return True
        except OSError:
            continue
    return False


def _write_cores_txt(path: str, dirs: List[str], pkg_map: Dict[str, List[str]]):
    """Write ``fusesoc-cores.txt`` — one absolute core-dir path per line.

    Each entry is preceded by a comment showing which package(s) it came from.
    """
    # Build reverse map: abs_dir -> [pkg_names]
    rev: Dict[str, List[str]] = {}
    for pkg_name, dirs_list in pkg_map.items():
        for d in dirs_list:
            rev.setdefault(d, []).append(pkg_name)
    with open(path, "w") as fp:
        fp.write("# Generated by IVPM fusesoc handler — do not edit manually\n")
        for d in dirs:
            pkgs = rev.get(d, ["unknown"])
            fp.write("# from: %s\n%s\n" % (", ".join(pkgs), d))


def _write_cores_envrc(path: str, dirs: List[str], project_dir: str):
    """Write ``fusesoc-cores.envrc`` — export ``FUSESOC_CORES``."""
    sep = os.pathsep
    core_paths = sep.join(dirs)
    with open(path, "w") as fp:
        fp.write("# Generated by IVPM fusesoc handler — do not edit manually\n")
        fp.write('export FUSESOC_CORES="%s"\n' % core_paths)


def _patch_packages_envrc(deps_dir: str):
    """Insert or replace the fusesoc section inside ``packages/packages.envrc``.

    Uses begin/end sentinel comments so the section can be reliably replaced
    on subsequent runs, regardless of whether the direnv handler regenerates
    the rest of the file.
    """
    envrc_path = os.path.join(deps_dir, "packages.envrc")
    if not os.path.isfile(envrc_path):
        return  # direnv handler not active; nothing to patch

    new_section = (
        "%s\n"
        "source_env ./fusesoc-cores.envrc\n"
        "%s\n"
    ) % (_SENTINEL_BEGIN, _SENTINEL_END)

    with open(envrc_path) as fp:
        content = fp.read()

    begin_idx = content.find(_SENTINEL_BEGIN)
    end_idx = content.find(_SENTINEL_END)

    if begin_idx != -1 and end_idx != -1:
        # Replace existing section
        end_of_line = content.find("\n", end_idx)
        if end_of_line == -1:
            end_of_line = len(content)
        else:
            end_of_line += 1  # include the newline
        new_content = content[:begin_idx] + new_section + content[end_of_line:]
    else:
        if begin_idx != -1 or end_idx != -1:
            # One sentinel present without the other — damaged state; append fresh
            _logger.warning(
                "packages.envrc has incomplete fusesoc sentinels; appending new section")
            new_content = content + "\n" + new_section
        else:
            new_content = content + "\n" + new_section

    with open(envrc_path, "w") as fp:
        fp.write(new_content)


def _patch_fusesoc_conf(conf_path: str, core_dirs: Dict[str, List[str]]):
    """Update ``fusesoc.conf`` with IVPM-managed library sections.

    Only ``[library.ivpm.*]`` sections are touched.  Stale sections (whose
    package is no longer in *core_dirs*) are removed.  All other sections
    are preserved.
    """
    cfg = configparser.ConfigParser()
    cfg.optionxform = str  # preserve case
    cfg.read(conf_path)

    # Collect current managed section names
    managed_names = set()
    for pkg_name, dirs in core_dirs.items():
        for idx, d in enumerate(dirs):
            section = "%s%s" % (_FUSESOC_CONF_PREFIX, pkg_name)
            if len(dirs) > 1:
                section = "%s-%d" % (section, idx)
            managed_names.add(section)

    # Remove stale IVPM-managed sections
    stale = [s for s in cfg.sections()
             if s.startswith(_FUSESOC_CONF_PREFIX) and s not in managed_names]
    for section in stale:
        cfg.remove_section(section)

    # Write/update current sections
    for pkg_name, dirs in core_dirs.items():
        for idx, d in enumerate(dirs):
            section = "%s%s" % (_FUSESOC_CONF_PREFIX, pkg_name)
            if len(dirs) > 1:
                section = "%s-%d" % (section, idx)
            if section not in cfg:
                cfg.add_section(section)
            cfg.set(section, "location", os.path.abspath(d))
            cfg.set(section, "sync-type", "local")

    with open(conf_path, "w") as fp:
        cfg.write(fp)


@dc.dataclass
class PackageHandlerFuseSoC(PackageHandler):
    name               = "fusesoc"
    description        = "Discovers .core dirs from deps; generates fusesoc-cores.envrc and fusesoc-cores.txt"
    leaf_when          = None
    root_when          = None
    phase              = 10   # after direnv (phase=0)
    conditions_summary = (
        "leaf: all non-PyPI packages; "
        "root: always (cleans stale entries even when no cores are present)"
    )

    # pkg_name -> list of absolute core dir paths
    _core_dirs: Dict[str, List[str]] = dc.field(default_factory=dict, init=False, repr=False)
    _prev_state: dict = dc.field(default_factory=dict, init=False, repr=False)
    _output_written: bool = dc.field(default=False, init=False, repr=False)

    @classmethod
    def handler_info(cls):
        from ..show.info_types import HandlerInfo
        return HandlerInfo(
            name=cls.name,
            description=cls.description,
            phase=cls.phase,
            conditions=(
                "leaf: non-PyPI packages that contain valid .core files "
                "(CAPI-2) or declare with.fusesoc.cores; "
                "root: always (cleans stale entries even when no cores remain)"
            ),
            notes=(
                "Discovers FuseSoC core directories from dependencies and "
                "generates packages/fusesoc-cores.envrc (FUSESOC_CORES), "
                "packages/fusesoc-cores.txt, and optionally contributes to "
                "packages/packages.envrc. "
                "When update-conf: true is set, also updates fusesoc.conf "
                "with [library.ivpm.*] sections."
            ),
        )

    def reset(self):
        self._core_dirs = {}
        self._output_written = False

    def on_root_pre_load(self, update_info: ProjectUpdateInfo):
        self.reset()
        self._prev_state = update_info.handler_state.get("fusesoc", {})

    def on_leaf_post_load(self, pkg: Package, update_info: ProjectUpdateInfo):
        if not hasattr(pkg, "path") or pkg.path is None:
            return
        if getattr(pkg, "src_type", None) == "pypi":
            return

        dirs = self._get_core_dirs(pkg)
        if dirs:
            with self._lock:
                self._core_dirs[pkg.name] = dirs

    def on_root_post_load(self, update_info: ProjectUpdateInfo):
        cfg = update_info.handler_configs.get("fusesoc", {}) or {}
        project_dir = update_info.project_dir or os.path.dirname(update_info.deps_dir)
        deps_dir = update_info.deps_dir

        # Filter by import list
        import_filter = cfg.get("import", "all")
        if import_filter == "all":
            dirs = [d for dirs in self._core_dirs.values() for d in dirs]
            active_pkg_map = dict(self._core_dirs)
        else:
            dirs = []
            active_pkg_map = {}
            for name in import_filter:
                pkg_dirs = self._core_dirs.get(name, [])
                dirs.extend(pkg_dirs)
                if pkg_dirs:
                    active_pkg_map[name] = pkg_dirs

        # Include project's own .core files
        if _has_cores_nonrecursive(project_dir):
            dirs = [project_dir] + dirs
            active_pkg_map["__project__"] = [project_dir]

        # Clean stale entries from the previous run
        self._cleanup_stale_outputs(deps_dir, active_pkg_map)

        if not dirs:
            return

        # Deduplicate while preserving order
        seen = set()
        deduped = []
        for d in dirs:
            abs_d = os.path.abspath(d)
            if abs_d not in seen:
                seen.add(abs_d)
                deduped.append(abs_d)
        dirs = deduped

        _write_cores_txt(os.path.join(deps_dir, "fusesoc-cores.txt"), dirs, active_pkg_map)
        _write_cores_envrc(os.path.join(deps_dir, "fusesoc-cores.envrc"), dirs, project_dir)
        _patch_packages_envrc(deps_dir)

        if cfg.get("update-conf", False):
            _patch_fusesoc_conf(
                os.path.join(project_dir, "fusesoc.conf"),
                active_pkg_map)

        self._output_written = True

        from ..utils import note
        pkg_count = len([k for k in active_pkg_map if k != "__project__"])
        note("Generated fusesoc-cores.envrc with %d core director%s from %d package%s" % (
            len(dirs), "y" if len(dirs) == 1 else "ies",
            pkg_count, "" if pkg_count == 1 else "s"))

    # ------------------------------------------------------------------ #

    def _get_core_dirs(self, pkg: Package) -> List[str]:
        """Return core dirs from explicit declaration or auto-detection."""
        patterns = self._get_declared_patterns(pkg)
        if patterns is not None:
            resolved = self._resolve_patterns(pkg.name, pkg.path, patterns)
            if not resolved:
                _logger.warning(
                    "Package %s declares with.fusesoc.cores but no valid "
                    ".core files matched", pkg.name)
            return resolved

        # Auto-detect: non-recursive scan of package root only
        if _has_cores_nonrecursive(pkg.path):
            return [pkg.path]

        return []

    def _get_declared_patterns(self, pkg: Package) -> Optional[List[str]]:
        """Return explicit cores patterns from dep's own ivpm.yaml, or None."""
        if not os.path.isfile(os.path.join(pkg.path, "ivpm.yaml")):
            return None
        try:
            from ..proj_info import ProjInfo
            info = ProjInfo.mkFromProj(pkg.path)
        except Exception:
            return None
        if info is None:
            return None
        cfg = info.handler_configs.get("fusesoc", {}) or {}
        patterns = cfg.get("cores", None)
        return [str(p) for p in patterns] if patterns is not None else None

    def _resolve_patterns(self, owner_name: str, root_dir: str,
                          patterns: List[str]) -> List[str]:
        """Resolve glob patterns to core dirs, validating each matched file."""
        found = []
        seen_dirs = set()

        for pattern in patterns:
            matches = sorted(_glob.glob(pattern, root_dir=root_dir, recursive=True))
            if not matches:
                _logger.warning(
                    "Package %s: fusesoc cores pattern '%s' matched no files",
                    owner_name, pattern)
                continue
            for match in matches:
                match_path = os.path.join(root_dir, match)
                if os.path.isfile(match_path) and match.endswith(".core"):
                    # Validate CAPI-2 before accepting
                    try:
                        with open(match_path, "rb") as fh:
                            head = fh.read(4096)
                        if b"CAPI=2" not in head:
                            _logger.debug(
                                "Package %s: %s is not a CAPI=2 core file; skipping",
                                owner_name, match)
                            continue
                    except OSError as e:
                        _logger.debug(
                            "Package %s: could not read %s: %s",
                            owner_name, match, e)
                        continue
                    core_dir = os.path.dirname(match_path)
                    if core_dir in seen_dirs:
                        continue
                    found.append(core_dir)
                    seen_dirs.add(core_dir)
                elif os.path.isdir(match_path):
                    # A directory pattern -- scan for .core files inside
                    if _has_cores_nonrecursive(match_path):
                        if match_path in seen_dirs:
                            continue
                        found.append(match_path)
                        seen_dirs.add(match_path)

        return found

    def get_state_entries(self) -> dict:
        """Persist core dirs so the next run can clean up stale entries."""
        if not self._output_written and not self._prev_state:
            return {}
        return {"core_dirs": {k: v for k, v in self._core_dirs.items()}}

    def _cleanup_stale_outputs(self, deps_dir: str, active_pkg_map: Dict[str, List[str]]):
        """Remove output files and stale fusesoc.conf sections.

        Removes fusesoc-cores.txt and fusesoc-cores.envrc when no cores exist.
        Removes the sentinel section from packages.envrc.
        Removes stale [library.ivpm.*] sections from fusesoc.conf when
        update-conf is active.
        """
        # Remove output files if no cores exist
        if not active_pkg_map:
            for name in ("fusesoc-cores.txt", "fusesoc-cores.envrc"):
                path = os.path.join(deps_dir, name)
                if os.path.isfile(path):
                    os.remove(path)

            # Remove sentinel section from packages.envrc
            envrc_path = os.path.join(deps_dir, "packages.envrc")
            if os.path.isfile(envrc_path):
                begin_sentinel = "%s\n" % _SENTINEL_BEGIN
                end_sentinel = "%s\n" % _SENTINEL_END
                with open(envrc_path) as fp:
                    content = fp.read()
                begin_idx = content.find(begin_sentinel)
                end_idx = content.find(end_sentinel)
                if begin_idx != -1 and end_idx != -1:
                    end_of_line = content.find("\n", end_idx)
                    if end_of_line == -1:
                        end_of_line = len(content)
                    else:
                        end_of_line += 1
                    new_content = content[:begin_idx] + content[end_of_line:]
                    with open(envrc_path, "w") as fp:
                        fp.write(new_content)
