#****************************************************************************
#* package_handler_node.py
#*
#* Copyright 2024 Matthew Ballance and Contributors
#*
#* Licensed under the Apache License, Version 2.0 (the "License"); you may
#* not use this file except in compliance with the License.
#* You may obtain a copy of the License at:
#*
#*   http://www.apache.org/licenses/LICENSE-2.0
#*
#* Unless required by applicable law or agreed to in writing, software
#* distributed under the License is distributed on an "AS IS" BASIS,
#* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#* See the License for the specific language governing permissions and
#* limitations under the License.
#****************************************************************************
import dataclasses as dc
import hashlib
import json
import logging
import os
import subprocess
from typing import ClassVar, Dict, List, Optional

from ..package import Package, get_type_data
from ..project_ops_info import ProjectUpdateInfo
from ..utils import note, fatal, getpkgdir, resolve_pkg_path
from ..msg import warning
from ..pkg_content_type import NodeTypeData
from ..installer_run import run_installer, format_output_tail
from ..content_attrib import (
    ENROLLED_EXPLICIT, ENROLLED_PROBE, ENROLLED_PROVIDES, ENROLLED_SRC_TYPE,
    OriginMap, isolate, isolation_identified_by,
    isolation_note, report_content_failure, report_manifest_problem,
    probe_allowed, report_probe_adoption, set_enrollment,
)
from ..manifest_check import check_node_manifest
from .package_handler import PackageHandler, HandlerFatalError
from .handler_phases import HandlerPhase

_logger = logging.getLogger("ivpm.handlers.package_handler_node")


def _strict(update_info) -> bool:
    """Whether --strict was given. Absent everywhere but the CLI, so read
    defensively: handlers are driven directly by tests and by the API."""
    args = getattr(update_info, "args", None)
    return bool(getattr(args, "strict", False))

_NODE_SENTINEL_BEGIN = "# --- ivpm:node begin ---"
_NODE_SENTINEL_END   = "# --- ivpm:node end ---"


def _write_node_envrc(node_dir: str):
    """Write the ``packages/node/export.envrc`` direnv snippet.

    IVPM delegates environment activation to ``direnv``; the same bash
    ``export.envrc`` is emitted on every platform (git-bash on Windows).
    """
    if not os.path.isdir(node_dir):
        return

    envrc_path = os.path.join(node_dir, "export.envrc")
    with open(envrc_path, "w") as fp:
        fp.write("# Generated by IVPM node handler -- do not edit manually\n")
        fp.write("PATH_add node_modules/.bin\n")
        # NODE_PATH covers CommonJS require() only -- the ESM resolver ignores
        # it. Importing the managed packages from project sources is what the
        # root node_modules symlink (with.node.link-root) is for.
        fp.write("export NODE_PATH=\"$PWD/node_modules\"\n")


def _patch_packages_envrc_node(deps_dir: str):
    """Insert or replace the node PATH/NODE_PATH section in packages activation files."""
    envrc_path = os.path.join(deps_dir, "packages.envrc")

    new_section = (
        "%s\n"
        "source_env ./node/export.envrc\n"
        "%s\n"
    ) % (_NODE_SENTINEL_BEGIN, _NODE_SENTINEL_END)

    if not os.path.isfile(envrc_path):
        with open(envrc_path, "w") as fp:
            fp.write("# Generated by IVPM -- do not edit manually\n")
            fp.write(new_section)
    else:
        with open(envrc_path) as fp:
            content = fp.read()

        begin_idx = content.find(_NODE_SENTINEL_BEGIN)
        end_idx   = content.find(_NODE_SENTINEL_END)

        if begin_idx != -1 and end_idx != -1:
            end_of_line = content.find("\n", end_idx)
            end_of_line = len(content) if end_of_line == -1 else end_of_line + 1
            new_content = content[:begin_idx] + new_section + content[end_of_line:]
        else:
            new_content = content + "\n" + new_section

        with open(envrc_path, "w") as fp:
            fp.write(new_content)


def _symlinks_supported(dest_parent: str) -> bool:
    """Return True if the filesystem at *dest_parent* supports symlinks."""
    probe = os.path.join(dest_parent, ".ivpm_symlink_probe")
    try:
        os.symlink(".", probe)
        os.remove(probe)
        return True
    except (OSError, NotImplementedError):
        return False


def _link_root_node_modules(project_root: str, node_modules_dir: str) -> Optional[str]:
    """Symlink ``<project_root>/node_modules`` at the managed node_modules.

    Node resolves a bare specifier by walking ``node_modules`` directories
    *upward from the importing file*; it never looks sideways into
    ``packages/node/``. Without this link, project sources cannot import the
    managed packages at all. ``NODE_PATH`` is not an alternative -- the ESM
    resolver ignores it, so it would cover ``require()`` and leave ``import``
    broken.

    Returns the link path on success, or None when nothing was linked.
    """
    link_path = os.path.join(project_root, "node_modules")

    if os.path.islink(link_path):
        if os.path.realpath(link_path) == os.path.realpath(node_modules_dir):
            return link_path
        # Points somewhere else (deps-dir moved, or a stale hand-made link).
        os.unlink(link_path)
    elif os.path.exists(link_path):
        # A real directory here is somebody's hand-managed install. Replacing it
        # would silently delete packages IVPM does not know about.
        note("WARNING: %s exists and is not an IVPM-managed symlink; leaving it "
             "in place. Packages installed by IVPM will not be importable from "
             "project sources. Remove it, or set with.node.link-root: false to "
             "silence this." % link_path)
        return None

    if not _symlinks_supported(project_root):
        note("WARNING: cannot create %s -- this filesystem does not support "
             "symlinks. Tool executables on PATH still work; importing the "
             "managed packages from project sources will not." % link_path)
        return None

    try:
        os.symlink(os.path.relpath(node_modules_dir, project_root),
                   link_path,
                   target_is_directory=True)
    except OSError as e:
        note("WARNING: could not create %s: %s" % (link_path, e))
        return None

    return link_path


def _unlink_root_node_modules(project_root: str, node_modules_dir: str,
                              dry_run: bool = False) -> Optional[str]:
    """Remove the root ``node_modules`` symlink created by this handler.

    Only ever removes a *symlink* that resolves to the managed tree; a real
    directory, or a link pointing elsewhere, belongs to somebody else.
    """
    link_path = os.path.join(project_root, "node_modules")
    if not os.path.islink(link_path):
        return None
    if os.path.realpath(link_path) != os.path.realpath(node_modules_dir):
        return None
    if not dry_run:
        os.unlink(link_path)
    return link_path


def _read_package_name(pkg_path: str, pkg=None) -> Optional[str]:
    """Return the ``name`` declared by the package.json in *pkg_path*.

    The dep key in the generated package.json must be the package's *real*
    name: npm happily installs a ``file:`` dep under whatever key it is given,
    but then the package is not importable under the name its own sources and
    dependants use.

    Returning None falls back to the directory name, which installs the
    package under a name nothing imports it by. That is worth a word: it is
    the one point in the node path where a malformed manifest is read and
    could be reported against a specific package.
    """
    path = os.path.join(pkg_path, "package.json")
    try:
        with open(path) as fp:
            name = json.load(fp).get("name")
    except (OSError, ValueError) as e:
        warning("could not read the package name from %s (%s); falling back "
                "to the directory name, which may not be the name this "
                "package is imported by" % (path, e),
                getattr(pkg, "srcinfo", None) if pkg is not None else None)
        return None
    return name if isinstance(name, str) and name else None


_NPM_NAMED_DEP_RE = (
    # "npm error notarget No matching version found for lodash@^99.0.0"
    r"No matching version found for (\S+?)@",
    # "npm error 404  'no-such-pkg@1.0.0' is not in this registry"
    r"404\s+'([^'@]+)@",
    # "npm error While resolving: my-pkg@1.0.0"
    r"While resolving:\s+(\S+?)@",
)


def _installer_failed_dep(lines) -> Optional[str]:
    """The dependency npm *said* it choked on, or None.

    A fast path, and nothing more. It reads npm's prose, so it breaks the
    moment npm rewords a message, and it says nothing at all about the many
    failures that name no dependency. None is an ordinary result; the caller
    must have another way to reach an answer.
    """
    import re
    for line in reversed(lines or []):
        for pattern in _NPM_NAMED_DEP_RE:
            m = re.search(pattern, line)
            if m:
                return m.group(1)
    return None


def _is_gitignored(path: str) -> bool:
    """Return True if *path* is gitignored (uses git check-ignore)."""
    try:
        result = subprocess.run(
            ["git", "check-ignore", "-q", path],
            capture_output=True,
        )
        return result.returncode == 0
    except Exception:
        return False


def _package_json_hash(path: str) -> str:
    """Return a hex digest of the contents of a package.json file, or ''.

    The empty string never matches a stored hash, so a read failure here
    silently forces a full reinstall on every single run. That is a real cost
    and it used to be invisible; say what happened, then take the safe path.
    """
    try:
        with open(path, "rb") as fp:
            return hashlib.sha256(fp.read()).hexdigest()
    except OSError as e:
        warning("could not read %s (%s); the node install cannot be skipped "
                "on an unchanged manifest and will re-run every time"
                % (path, e))
        return ""


@dc.dataclass
class PackageHandlerNode(PackageHandler):
    name:               ClassVar[str]            = "node"
    description:        ClassVar[str]            = "Installs Node.js packages into the managed node environment"
    leaf_when:          ClassVar[Optional[List]] = None
    root_when:          ClassVar[Optional[List]] = None
    phase:              ClassVar[str]            = HandlerPhase.INSTALL
    conditions_summary: ClassVar[str]            = ("leaf: all packages; "
                                                     "root: always (skips if no Node packages and no node config)")

    _npm_pkgs:           Dict[str, object] = dc.field(default_factory=dict)
    _source_pkgs:        Dict[str, object] = dc.field(default_factory=dict)
    _explicit_names:     set               = dc.field(default_factory=set)
    _prev_pkg_json_hash: str               = dc.field(default="")
    _current_pkg_json_hash: str            = dc.field(default="")
    # Which generated package.json dependency came from which package.
    # Recorded as the manifest is synthesised, where the Package is in hand.
    _origins:            OriginMap         = dc.field(default_factory=OriginMap)

    def reset(self):
        self._npm_pkgs = {}
        self._source_pkgs = {}
        self._explicit_names = set()
        self._prev_pkg_json_hash = ""
        self._current_pkg_json_hash = ""
        self._origins = OriginMap()

    @classmethod
    def handler_info(cls):
        from ..show.info_types import HandlerInfo, ParamInfo
        return HandlerInfo(
            name=cls.name,
            description=cls.description,
            phase=cls.phase,
            conditions=cls.conditions_summary,
            params=[
                ParamInfo("src: npm", "Install a package from the npm registry"),
                ParamInfo("src: package.json", "Import npm deps from an existing package.json"),
                ParamInfo("type: node", "Link a source package into the node environment"),
            ],
        )

    # ------------------------------------------------------------------
    # Leaf callbacks
    # ------------------------------------------------------------------

    def on_leaf_post_load(self, pkg: Package, update_info: ProjectUpdateInfo):
        from ..pkg_types.package_npm import PackageNpm
        from ..pkg_types.package_packagejson import PackagePackageJson

        # Virtual nodes (e.g. `src: ivpm.yaml` factories) have no installed
        # directory to scan -- they only contribute deps.
        if getattr(pkg, "virtual", False):
            return

        if pkg.src_type == "npm":
            set_enrollment(pkg, "node", ENROLLED_SRC_TYPE)
            with self._lock:
                self._npm_pkgs[pkg.name] = pkg
                self._explicit_names.add(pkg.name)
            return

        node_data = get_type_data(pkg, NodeTypeData)
        if node_data is not None:
            # Fill in the unspecified fields now that merging is over. Past
            # this point the handler works with concrete values.
            node_data = node_data.resolved()
            # 'type: node' at the dependency entry, or the package's own
            # ivpm.yaml declaring it. Which one decides where a later failure
            # is located, so keep them apart.
            set_enrollment(pkg, "node",
                           ENROLLED_PROVIDES
                           if getattr(node_data, "self_declared", False)
                           else ENROLLED_EXPLICIT)
            with self._lock:
                self._source_pkgs[pkg.name] = (pkg, node_data)
                self._explicit_names.add(pkg.name)
            return

        if pkg.src_type == "package.json":
            self._harvest_packagejson_pkg(pkg, update_info)
            return

        # Auto-detection: source packages (git/dir/http) without an explicit
        # type that contain an *installable* package.json. A package.json
        # existing is not the same as npm being able to install from it: a
        # workspace root, or one with no name, is valid JSON and not a
        # dependency. Rejecting those here costs the user nothing.
        if (pkg.src_type in ("git", "dir", "http", "gh-rls") and
                probe_allowed(pkg, "node") and
                hasattr(pkg, "path") and pkg.path):
            diag = check_node_manifest(pkg.path)
            if diag is not None:
                set_enrollment(pkg, "node", ENROLLED_PROBE,
                               evidence="package.json")
                if diag.ok:
                    td = NodeTypeData().resolved()  # dev=False, link=True
                    report_probe_adoption(pkg, "node",
                                          evidence="package.json",
                                          strict=_strict(update_info))
                    with self._lock:
                        self._source_pkgs[pkg.name] = (pkg, td)
                else:
                    report_manifest_problem(pkg, diag, "node",
                                            strict=_strict(update_info))

    def _harvest_packagejson_pkg(self, pkg, update_info: ProjectUpdateInfo):
        """Read a package.json URL and synthesize PackageNpm entries."""
        from ..pkg_types.package_npm import PackageNpm

        # Base for resolving a relative json_path. The old os.getcwd() fallback
        # was wrong in any mode -- the cwd need not be the project. In toolchain
        # mode the deps-dir is the root, so it is the correct base.
        proj_dir = update_info.project_root_or_none() or update_info.deps_dir

        json_path = getattr(pkg, "json_path", None)
        if json_path:
            # Expand env vars and resolve relative paths against the ivpm.yaml
            # that declared the entry -- not against the root project.
            path = resolve_pkg_path(pkg, json_path, proj_dir)
        else:
            url = getattr(pkg, "url", None)
            if not url:
                # Default to the declaring package's package.json when no url is given
                url = os.path.join(getpkgdir(pkg, proj_dir), "package.json")
                _logger.debug(
                    "src: package.json entry '%s' has no url — defaulting to '%s'",
                    pkg.name, url)

            # Resolve file:// URLs and ${VAR} substitutions
            path = url
            if path.startswith("file://"):
                path = path[len("file://"):]
            path = resolve_pkg_path(pkg, path, proj_dir)

        if not os.path.isfile(path):
            raise HandlerFatalError(
                "src: package.json entry '%s' references a package.json that "
                "does not exist: '%s'" % (pkg.name, path))

        try:
            with open(path) as fp:
                data = json.load(fp)
        except Exception as e:
            raise HandlerFatalError(
                "src: package.json entry '%s' could not read package.json at "
                "'%s': %s" % (pkg.name, path, e))

        with self._lock:
            for dep_name, version in data.get("dependencies", {}).items():
                if dep_name not in self._explicit_names:
                    synth = PackageNpm(dep_name)
                    synth.src_type = "npm"
                    synth.version = version
                    synth.dev = False
                    self._npm_pkgs.setdefault(dep_name, synth)

            for dep_name, version in data.get("devDependencies", {}).items():
                if dep_name not in self._explicit_names:
                    synth = PackageNpm(dep_name)
                    synth.src_type = "npm"
                    synth.version = version
                    synth.dev = True
                    self._npm_pkgs.setdefault(dep_name, synth)

    # ------------------------------------------------------------------
    # Root callbacks
    # ------------------------------------------------------------------

    def on_root_pre_load(self, update_info: ProjectUpdateInfo):
        self.reset()
        # Load previous handler state (hash of last generated package.json)
        state = update_info.handler_state.get("node", {})
        self._prev_pkg_json_hash = state.get("package_json_hash", "")

    def on_destroy(self, remove_info):
        """Remove the managed Node environment (packages/node, which holds
        node_modules and the generated activation files) along with the root
        node_modules symlink pointing into it. Honors dry_run."""
        node_dir = os.path.join(remove_info.deps_dir, "node")
        if not os.path.isdir(node_dir):
            return None

        dry_run = getattr(remove_info, "dry_run", False)
        removed = []

        # Drop the root symlink first: once node_dir is gone it dangles, and a
        # dangling link still resolves-compares equal, but removing it before
        # the target keeps the check meaningful.
        project_root = remove_info.project_root_or_none()
        if project_root is not None:
            link = _unlink_root_node_modules(
                project_root, os.path.join(node_dir, "node_modules"),
                dry_run=dry_run)
            if link is not None:
                removed.append(link)

        removed.append(node_dir)
        if not dry_run:
            from ..package import _rmtree_force
            _rmtree_force(node_dir)
        return removed

    def on_root_post_load(self, update_info: ProjectUpdateInfo):
        has_node_pkgs = bool(self._npm_pkgs or self._source_pkgs)
        node_config = getattr(update_info, "node_config", None)

        if not has_node_pkgs and node_config is None:
            return

        # Determine package manager
        manager = "npm"
        if node_config is not None and node_config.manager:
            manager = node_config.manager

        deps_dir = update_info.deps_dir
        node_dir = os.path.join(deps_dir, "node")
        os.makedirs(node_dir, exist_ok=True)

        # Write .nvmrc if version is specified
        if node_config is not None and node_config.version:
            nvmrc_path = os.path.join(node_dir, ".nvmrc")
            with open(nvmrc_path, "w") as fp:
                fp.write(node_config.version + "\n")

        # Generate packages/node/package.json
        pkg_json_path = os.path.join(node_dir, "package.json")
        self._write_package_json(pkg_json_path, node_dir)

        # Compare hash — skip npm install if package.json unchanged and node_modules exists
        new_hash = _package_json_hash(pkg_json_path)
        node_modules_dir = os.path.join(node_dir, "node_modules")
        install_needed = (
            new_hash != self._prev_pkg_json_hash
            or not os.path.isdir(node_modules_dir)
        )
        self._current_pkg_json_hash = new_hash

        # Run install (only when needed)
        if install_needed:
            with self.task_context(update_info, "node-install", "Installing Node.js packages") as task:
                self._run_install(manager, node_dir, update_info)
        else:
            note("Node packages unchanged — skipping npm install")

        # Make the managed packages importable from project sources. Only in
        # WORKSPACE mode: a toolchain deps-dir is the root and has no project
        # sources above it, so a node_modules there would link nothing to
        # nothing.
        link_root = node_config.link_root if node_config is not None else True
        project_root = update_info.project_root_or_none()
        if link_root and project_root is not None and os.path.isdir(node_modules_dir):
            _link_root_node_modules(project_root, node_modules_dir)

        # Patch packages.envrc
        emit_env = node_config.env if node_config is not None else True
        if emit_env:
            _write_node_envrc(node_dir)
            _patch_packages_envrc_node(deps_dir)

        # Warn if lockfile is gitignored
        lockfile = os.path.join(node_dir, "package-lock.json")
        if manager == "npm" and os.path.isfile(lockfile) and _is_gitignored(lockfile):
            note("WARNING: packages/node/package-lock.json is gitignored. "
                 "Consider committing it for reproducible builds.")

    def _write_package_json(self, path: str, node_dir: str):
        """Synthesise packages/node/package.json from collected packages.

        Source packages (``type: node`` with ``link: true``) are emitted as
        ``file:`` dependencies rather than being linked by a separate command.
        npm symlinks a ``file:`` dep, so this is still an editable install --
        but it happens as part of the one install, it puts the package's
        executables in ``node_modules/.bin`` along with everything else, and it
        is recorded in the lockfile instead of being invisible to it.
        """
        deps = {}
        dev_deps = {}

        def record(dep_name, spec, pkg):
            # The generated manifest is just JSON once written; this is the
            # only point at which a dependency key and the package that
            # contributed it are both in hand.
            self._origins.record("%s@%s" % (dep_name, spec), pkg, "node",
                                 language="node", dist=dep_name)

        for name, pkg in self._npm_pkgs.items():
            if pkg.dev:
                dev_deps[name] = pkg.version
            else:
                deps[name] = pkg.version
            record(name, pkg.version, pkg)

        for pkg_name, (pkg, node_data) in self._source_pkgs.items():
            # link: false means "track the source but keep it out of the node
            # environment" -- it is not a request for a non-editable install.
            if not node_data.link:
                continue
            pkg_path = getattr(pkg, "path", None)
            if not pkg_path:
                continue
            # Relative so the whole tree stays relocatable: the symlinks npm
            # creates from a relative file: spec are themselves relative.
            spec = "file:" + os.path.relpath(pkg_path, node_dir).replace(os.sep, "/")
            dep_name = _read_package_name(pkg_path, pkg) or pkg_name
            if node_data.dev:
                dev_deps[dep_name] = spec
            else:
                deps[dep_name] = spec
            record(dep_name, spec, pkg)

        data = {
            "name": "ivpm-node-env",
            "version": "1.0.0",
            "private": True,
        }
        if deps:
            data["dependencies"] = deps
        if dev_deps:
            data["devDependencies"] = dev_deps

        with open(path, "w") as fp:
            json.dump(data, fp, indent=2)
            fp.write("\n")

    def _run_install(self, manager: str, node_dir: str, update_info: ProjectUpdateInfo):
        """Run the appropriate package manager install command."""
        suppress = getattr(update_info, "suppress_output", False)
        if manager == "npm":
            cmd = ["npm", "install", "--prefix", node_dir]
        elif manager == "pnpm":
            cmd = ["pnpm", "install", "--dir", node_dir]
        elif manager == "yarn":
            cmd = ["yarn", "install", "--cwd", node_dir]
        else:
            fatal("Unknown node package manager: %s" % manager)

        _logger.info("Running: %s", " ".join(cmd))

        # Captured whether or not it is displayed: suppress_output used to mean
        # DEVNULL, which destroyed the only account of why the install failed
        # at precisely the moment it mattered.
        result = run_installer(cmd, quiet=suppress)

        if result.returncode == 127:
            fatal("'%s' not found — please install Node.js and %s" % (manager, manager))
        elif not result.ok:
            self._report_install_failure(cmd, result, update_info,
                                         manager, node_dir)

    def _report_install_failure(self, cmd, result, update_info,
                                manager=None, node_dir=None):
        """Attribute a failed node install and report it. Always raises.

        npm does sometimes name the offending dependency (``ETARGET``, a 404,
        a resolution trace), and when it does the fast path below finds it in
        one step. When it does not -- which covers most of the interesting
        cases, including the malformed ``package.json`` in a ``file:`` dep
        that prompted all of this -- each dependency is installed on its own
        until the culprit falls out. That second route asks only *which*, so
        it is indifferent to how npm words things or to what went wrong.
        """
        pkgs_by_key = getattr(update_info, "all_pkgs_by_key", None) or {}
        output = format_output_tail(result.lines)

        contributors = self._origins.by_group("node")

        origins = []
        identified_by = None
        note_text = None

        dist = _installer_failed_dep(result.lines)
        if dist is not None:
            origin = self._origins.resolve_dist(dist, group="node")
            if origin is not None:
                origins = [origin]
                identified_by = "npm named '%s' in its output" % dist

        if not origins and len(contributors) > 1 and node_dir:
            iso = isolate(
                contributors,
                lambda o: self._retry_one(o, manager or "npm", node_dir))
            if iso.culprits:
                origins = iso.culprits
            identified_by = isolation_identified_by(iso)
            note_text = isolation_note(iso)

        if not origins:
            origins = contributors
            if identified_by is None and origins:
                identified_by = "every package in the node environment"

        if not origins:
            fatal("Node package install failed (exit %d): %s%s" % (
                result.returncode, " ".join(cmd), output))
            return

        report_content_failure(
            "node", origins, pkgs_by_key,
            group=os.path.join(node_dir or "", "package.json"),
            installer="%s (exit %d)" % (" ".join(cmd), result.returncode),
            output=output,
            identified_by=identified_by,
            note_text=note_text)

    def _retry_one(self, origin, manager: str, node_dir: str) -> bool:
        """Install a single dependency by itself; True if it succeeds.

        Done in a scratch prefix rather than in the real node environment: the
        diagnostic pass must not further disturb a ``node_modules`` the user
        will want to look at, and installing one dependency into the real
        prefix would prune everything else out of it.

        ``file:`` specs are rewritten to absolute paths. The generated
        manifest keeps them relative so the workspace stays relocatable, but a
        relative path resolved from the scratch directory points nowhere --
        which would make every source package look broken.
        """
        import shutil
        import tempfile

        dep_name = origin.dist or origin.name
        spec = origin.spec
        if spec.startswith(dep_name + "@"):
            spec = spec[len(dep_name) + 1:]

        if spec.startswith("file:"):
            rel = spec[len("file:"):]
            spec = "file:" + os.path.abspath(os.path.join(node_dir, rel))

        scratch = tempfile.mkdtemp(prefix="ivpm_node_isolate_")
        try:
            with open(os.path.join(scratch, "package.json"), "w") as fp:
                json.dump({
                    "name": "ivpm-node-isolate",
                    "version": "1.0.0",
                    "private": True,
                    "dependencies": {dep_name: spec},
                }, fp, indent=2)

            if manager == "pnpm":
                cmd = ["pnpm", "install", "--dir", scratch]
            elif manager == "yarn":
                cmd = ["yarn", "install", "--cwd", scratch]
            else:
                cmd = ["npm", "install", "--prefix", scratch]

            return run_installer(cmd, quiet=True).ok
        finally:
            shutil.rmtree(scratch, ignore_errors=True)

    # ------------------------------------------------------------------
    # State persistence
    # ------------------------------------------------------------------

    def get_state_entries(self) -> dict:
        installed = list(self._npm_pkgs.keys()) + list(self._source_pkgs.keys())
        return {
            "manager": "npm",
            "installed": sorted(installed),
            "package_json_hash": self._current_pkg_json_hash,
        }
