#****************************************************************************
#* package_handler_modules.py
#*
#* Copyright 2024 Matthew Ballance and Contributors
#*
#* Licensed under the Apache License, Version 2.0 (the "License"); you may
#* not use this file except in compliance with the License.
#* You may obtain a copy of the License at:
#*
#*   http://www.apache.org/licenses/LICENSE-2.0
#*
#* Unless required by applicable law or agreed to in writing, software
#* distributed under the License is distributed on an "AS IS" BASIS,
#* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#* See the License for the specific language governing permissions and
#* limitations under the License.
#*
#****************************************************************************
"""
PackageHandlerModules -- collects module-typed packages and generates
``modules.envrc`` / patches ``packages.envrc``.
"""
import dataclasses as dc
import logging
import os
from typing import Dict

from ..package import Package
from ..project_ops_info import ProjectUpdateInfo
from .package_handler import PackageHandler

_logger = logging.getLogger("ivpm.handlers.package_handler_modules")

# Sentinel markers for the modules section inside packages/packages.envrc
_MODULES_SENTINEL_BEGIN = "# --- ivpm:modules begin ---"
_MODULES_SENTINEL_END   = "# --- ivpm:modules end ---"


@dc.dataclass
class PackageHandlerModules(PackageHandler):
    """Handler that generates module load statements into modules.envrc."""
    name               = "modules"
    description        = "Generates module load statements into modules.envrc"
    leaf_when          = None        # inspect every package
    root_when          = None        # always run on_root_post_load
    phase              = 1           # after direnv (0), before python (5)
    conditions_summary = "Active when any package carries ModuleTypeData"

    # pkg_name -> module specifier (e.g. "gcc/15.2.0")
    module_pkgs: Dict[str, str] = dc.field(default_factory=dict, init=False, repr=False)

    @classmethod
    def handler_info(cls):
        from ..show.info_types import HandlerInfo
        return HandlerInfo(
            name=cls.name,
            description=cls.description,
            phase=cls.phase,
            conditions=cls.conditions_summary or "",
            notes=(
                "Discovers packages with ModuleTypeData and generates "
                "packages/modules.envrc with 'module load' statements. "
                "Also patches packages/packages.envrc with a sentinel-wrapped "
                "section that sources modules.envrc."
            ),
        )

    def reset(self):
        self.module_pkgs = {}

    def on_root_pre_load(self, update_info: ProjectUpdateInfo):
        self.reset()

    def on_leaf_post_load(self, pkg: Package, update_info: ProjectUpdateInfo):
        from ..package import get_type_data
        from ..pkg_content_type import ModuleTypeData
        td = get_type_data(pkg, ModuleTypeData)
        if td is None:
            return
        if not td.load:
            return
        module_spec = td.module or getattr(pkg, 'module', None) or pkg.name
        if module_spec is None:
            return
        with self._lock:
            self.module_pkgs[pkg.name] = module_spec

    def on_root_post_load(self, update_info: ProjectUpdateInfo):
        deps_dir = update_info.deps_dir

        if not self.module_pkgs:
            self._cleanup(deps_dir)
            return

        # Generate modules.envrc
        envrc_path = os.path.join(deps_dir, "modules.envrc")
        with open(envrc_path, "w") as fp:
            fp.write("# Generated by IVPM modules handler -- do not edit manually\n")
            for pkg_name in sorted(self.module_pkgs.keys()):
                fp.write("module load %s\n" % self.module_pkgs[pkg_name])

        # Patch packages.envrc
        _patch_packages_envrc(deps_dir)

        from ..utils import note
        note("Generated modules.envrc with %d module load statement%s" % (
            len(self.module_pkgs),
            "" if len(self.module_pkgs) == 1 else "s"))

    def _cleanup(self, deps_dir: str):
        """Remove modules.envrc and sentinel section from packages.envrc."""
        envrc_path = os.path.join(deps_dir, "modules.envrc")
        if os.path.isfile(envrc_path):
            os.remove(envrc_path)

        # Remove sentinel section from packages.envrc
        pkg_envrc = os.path.join(deps_dir, "packages.envrc")
        if os.path.isfile(pkg_envrc):
            _remove_sentinel_section(pkg_envrc)

    def get_lock_entries(self, deps_dir: str) -> dict:
        if not self.module_pkgs:
            return {}
        entries = {}
        for pkg_name, module_spec in sorted(self.module_pkgs.items()):
            entries[pkg_name] = {"module": module_spec}
        return {"modules": entries}

    def get_state_entries(self) -> dict:
        if not self.module_pkgs:
            return {}
        return {"module_pkgs": dict(self.module_pkgs)}


# ---------------------------------------------------------------------- #
# Helper functions                                                        #
# ---------------------------------------------------------------------- #

def _patch_packages_envrc(deps_dir: str):
    """Insert or replace the modules section inside ``packages/packages.envrc``."""
    envrc_path = os.path.join(deps_dir, "packages.envrc")
    if not os.path.isfile(envrc_path):
        return  # direnv handler not active

    new_section = (
        "%s\n"
        "source_env ./modules.envrc\n"
        "%s\n"
    ) % (_MODULES_SENTINEL_BEGIN, _MODULES_SENTINEL_END)

    with open(envrc_path) as fp:
        content = fp.read()

    begin_idx = content.find(_MODULES_SENTINEL_BEGIN)
    end_idx = content.find(_MODULES_SENTINEL_END)

    if begin_idx != -1 and end_idx != -1:
        # Replace existing section
        end_of_line = content.find("\n", end_idx)
        if end_of_line == -1:
            end_of_line = len(content)
        else:
            end_of_line += 1
        new_content = content[:begin_idx] + new_section + content[end_of_line:]
    else:
        if begin_idx != -1 or end_idx != -1:
            _logger.warning(
                "packages.envrc has incomplete modules sentinels; appending new section")
        new_content = content + "\n" + new_section

    with open(envrc_path, "w") as fp:
        fp.write(new_content)


def _remove_sentinel_section(envrc_path: str):
    """Remove the modules sentinel section from packages.envrc."""
    with open(envrc_path) as fp:
        content = fp.read()

    begin_idx = content.find(_MODULES_SENTINEL_BEGIN)
    end_idx = content.find(_MODULES_SENTINEL_END)

    if begin_idx != -1 and end_idx != -1:
        end_of_line = content.find("\n", end_idx)
        if end_of_line == -1:
            end_of_line = len(content)
        else:
            end_of_line += 1
        # Also remove the preceding newline if present
        if begin_idx > 0 and content[begin_idx - 1] == "\n":
            begin_idx -= 1
        new_content = content[:begin_idx] + content[end_of_line:]
        with open(envrc_path, "w") as fp:
            fp.write(new_content)
