#****************************************************************************
#* package_handler_node.py
#*
#* Copyright 2024 Matthew Ballance and Contributors
#*
#* Licensed under the Apache License, Version 2.0 (the "License"); you may
#* not use this file except in compliance with the License.
#* You may obtain a copy of the License at:
#*
#*   http://www.apache.org/licenses/LICENSE-2.0
#*
#* Unless required by applicable law or agreed to in writing, software
#* distributed under the License is distributed on an "AS IS" BASIS,
#* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#* See the License for the specific language governing permissions and
#* limitations under the License.
#****************************************************************************
import dataclasses as dc
import hashlib
import json
import logging
import os
import subprocess
from typing import ClassVar, Dict, List, Optional

from ..package import Package, get_type_data
from ..project_ops_info import ProjectUpdateInfo
from ..utils import note, fatal, getpkgdir, resolve_pkg_path
from ..pkg_content_type import NodeTypeData
from .package_handler import PackageHandler, HandlerFatalError
from .handler_phases import HandlerPhase

_logger = logging.getLogger("ivpm.handlers.package_handler_node")

_NODE_SENTINEL_BEGIN = "# --- ivpm:node begin ---"
_NODE_SENTINEL_END   = "# --- ivpm:node end ---"


def _write_node_envrc(node_dir: str):
    """Write the ``packages/node/export.envrc`` direnv snippet.

    IVPM delegates environment activation to ``direnv``; the same bash
    ``export.envrc`` is emitted on every platform (git-bash on Windows).
    """
    if not os.path.isdir(node_dir):
        return

    envrc_path = os.path.join(node_dir, "export.envrc")
    with open(envrc_path, "w") as fp:
        fp.write("# Generated by IVPM node handler -- do not edit manually\n")
        fp.write("PATH_add node_modules/.bin\n")
        fp.write("export NODE_PATH=\"$PWD/node_modules\"\n")


def _patch_packages_envrc_node(deps_dir: str):
    """Insert or replace the node PATH/NODE_PATH section in packages activation files."""
    envrc_path = os.path.join(deps_dir, "packages.envrc")

    new_section = (
        "%s\n"
        "source_env ./node/export.envrc\n"
        "%s\n"
    ) % (_NODE_SENTINEL_BEGIN, _NODE_SENTINEL_END)

    if not os.path.isfile(envrc_path):
        with open(envrc_path, "w") as fp:
            fp.write("# Generated by IVPM -- do not edit manually\n")
            fp.write(new_section)
    else:
        with open(envrc_path) as fp:
            content = fp.read()

        begin_idx = content.find(_NODE_SENTINEL_BEGIN)
        end_idx   = content.find(_NODE_SENTINEL_END)

        if begin_idx != -1 and end_idx != -1:
            end_of_line = content.find("\n", end_idx)
            end_of_line = len(content) if end_of_line == -1 else end_of_line + 1
            new_content = content[:begin_idx] + new_section + content[end_of_line:]
        else:
            new_content = content + "\n" + new_section

        with open(envrc_path, "w") as fp:
            fp.write(new_content)


def _is_gitignored(path: str) -> bool:
    """Return True if *path* is gitignored (uses git check-ignore)."""
    try:
        result = subprocess.run(
            ["git", "check-ignore", "-q", path],
            capture_output=True,
        )
        return result.returncode == 0
    except Exception:
        return False


def _package_json_hash(path: str) -> str:
    """Return a hex digest of the contents of a package.json file, or '' on error."""
    try:
        with open(path, "rb") as fp:
            return hashlib.sha256(fp.read()).hexdigest()
    except Exception:
        return ""


@dc.dataclass
class PackageHandlerNode(PackageHandler):
    name:               ClassVar[str]            = "node"
    description:        ClassVar[str]            = "Installs Node.js packages into the managed node environment"
    leaf_when:          ClassVar[Optional[List]] = None
    root_when:          ClassVar[Optional[List]] = None
    phase:              ClassVar[str]            = HandlerPhase.INSTALL
    conditions_summary: ClassVar[str]            = ("leaf: all packages; "
                                                     "root: always (skips if no Node packages and no node config)")

    _npm_pkgs:           Dict[str, object] = dc.field(default_factory=dict)
    _source_pkgs:        Dict[str, object] = dc.field(default_factory=dict)
    _explicit_names:     set               = dc.field(default_factory=set)
    _prev_pkg_json_hash: str               = dc.field(default="")
    _current_pkg_json_hash: str            = dc.field(default="")

    def reset(self):
        self._npm_pkgs = {}
        self._source_pkgs = {}
        self._explicit_names = set()
        self._prev_pkg_json_hash = ""
        self._current_pkg_json_hash = ""

    @classmethod
    def handler_info(cls):
        from ..show.info_types import HandlerInfo, ParamInfo
        return HandlerInfo(
            name=cls.name,
            description=cls.description,
            phase=cls.phase,
            conditions=cls.conditions_summary,
            params=[
                ParamInfo("src: npm", "Install a package from the npm registry"),
                ParamInfo("src: package.json", "Import npm deps from an existing package.json"),
                ParamInfo("type: node", "Link a source package into the node environment"),
            ],
        )

    # ------------------------------------------------------------------
    # Leaf callbacks
    # ------------------------------------------------------------------

    def on_leaf_post_load(self, pkg: Package, update_info: ProjectUpdateInfo):
        from ..pkg_types.package_npm import PackageNpm
        from ..pkg_types.package_packagejson import PackagePackageJson

        # Virtual nodes (e.g. `src: ivpm.yaml` factories) have no installed
        # directory to scan -- they only contribute deps.
        if getattr(pkg, "virtual", False):
            return

        if pkg.src_type == "npm":
            with self._lock:
                self._npm_pkgs[pkg.name] = pkg
                self._explicit_names.add(pkg.name)
            return

        node_data = get_type_data(pkg, NodeTypeData)
        if node_data is not None:
            with self._lock:
                self._source_pkgs[pkg.name] = (pkg, node_data)
                self._explicit_names.add(pkg.name)
            return

        if pkg.src_type == "package.json":
            self._harvest_packagejson_pkg(pkg, update_info)
            return

        # Auto-detection: source packages (git/dir/http) without an explicit type
        # that contain a package.json are treated as node source packages.
        if (pkg.src_type in ("git", "dir", "http", "gh-rls") and
                getattr(pkg, "pkg_type", None) is None and
                hasattr(pkg, "path") and pkg.path):
            if os.path.isfile(os.path.join(pkg.path, "package.json")):
                td = NodeTypeData()  # defaults: dev=False, link=True
                with self._lock:
                    self._source_pkgs[pkg.name] = (pkg, td)

    def _harvest_packagejson_pkg(self, pkg, update_info: ProjectUpdateInfo):
        """Read a package.json URL and synthesize PackageNpm entries."""
        from ..pkg_types.package_npm import PackageNpm

        # Base for resolving a relative json_path. The old os.getcwd() fallback
        # was wrong in any mode -- the cwd need not be the project. In toolchain
        # mode the deps-dir is the root, so it is the correct base.
        proj_dir = update_info.project_root_or_none() or update_info.deps_dir

        json_path = getattr(pkg, "json_path", None)
        if json_path:
            # Expand env vars and resolve relative paths against the ivpm.yaml
            # that declared the entry -- not against the root project.
            path = resolve_pkg_path(pkg, json_path, proj_dir)
        else:
            url = getattr(pkg, "url", None)
            if not url:
                # Default to the declaring package's package.json when no url is given
                url = os.path.join(getpkgdir(pkg, proj_dir), "package.json")
                _logger.debug(
                    "src: package.json entry '%s' has no url — defaulting to '%s'",
                    pkg.name, url)

            # Resolve file:// URLs and ${VAR} substitutions
            path = url
            if path.startswith("file://"):
                path = path[len("file://"):]
            path = resolve_pkg_path(pkg, path, proj_dir)

        if not os.path.isfile(path):
            raise HandlerFatalError(
                "src: package.json entry '%s' references a package.json that "
                "does not exist: '%s'" % (pkg.name, path))

        try:
            with open(path) as fp:
                data = json.load(fp)
        except Exception as e:
            raise HandlerFatalError(
                "src: package.json entry '%s' could not read package.json at "
                "'%s': %s" % (pkg.name, path, e))

        with self._lock:
            for dep_name, version in data.get("dependencies", {}).items():
                if dep_name not in self._explicit_names:
                    synth = PackageNpm(dep_name)
                    synth.src_type = "npm"
                    synth.version = version
                    synth.dev = False
                    self._npm_pkgs.setdefault(dep_name, synth)

            for dep_name, version in data.get("devDependencies", {}).items():
                if dep_name not in self._explicit_names:
                    synth = PackageNpm(dep_name)
                    synth.src_type = "npm"
                    synth.version = version
                    synth.dev = True
                    self._npm_pkgs.setdefault(dep_name, synth)

    # ------------------------------------------------------------------
    # Root callbacks
    # ------------------------------------------------------------------

    def on_root_pre_load(self, update_info: ProjectUpdateInfo):
        self.reset()
        # Load previous handler state (hash of last generated package.json)
        state = update_info.handler_state.get("node", {})
        self._prev_pkg_json_hash = state.get("package_json_hash", "")

    def on_destroy(self, remove_info):
        """Remove the managed Node environment (packages/node, which holds
        node_modules and the generated activation files). Honors dry_run."""
        node_dir = os.path.join(remove_info.deps_dir, "node")
        if not os.path.isdir(node_dir):
            return None
        if getattr(remove_info, "dry_run", False):
            return [node_dir]
        from ..package import _rmtree_force
        _rmtree_force(node_dir)
        return [node_dir]

    def on_root_post_load(self, update_info: ProjectUpdateInfo):
        has_node_pkgs = bool(self._npm_pkgs or self._source_pkgs)
        node_config = getattr(update_info, "node_config", None)

        if not has_node_pkgs and node_config is None:
            return

        # Determine package manager
        manager = "npm"
        if node_config is not None and node_config.manager:
            manager = node_config.manager

        deps_dir = update_info.deps_dir
        node_dir = os.path.join(deps_dir, "node")
        os.makedirs(node_dir, exist_ok=True)

        # Write .nvmrc if version is specified
        if node_config is not None and node_config.version:
            nvmrc_path = os.path.join(node_dir, ".nvmrc")
            with open(nvmrc_path, "w") as fp:
                fp.write(node_config.version + "\n")

        # Generate packages/node/package.json
        pkg_json_path = os.path.join(node_dir, "package.json")
        self._write_package_json(pkg_json_path)

        # Compare hash — skip npm install if package.json unchanged and node_modules exists
        new_hash = _package_json_hash(pkg_json_path)
        node_modules_dir = os.path.join(node_dir, "node_modules")
        install_needed = (
            new_hash != self._prev_pkg_json_hash
            or not os.path.isdir(node_modules_dir)
        )
        self._current_pkg_json_hash = new_hash

        # Run install (only when needed)
        if install_needed:
            with self.task_context(update_info, "node-install", "Installing Node.js packages") as task:
                self._run_install(manager, node_dir, update_info)
        else:
            note("Node packages unchanged — skipping npm install")

        # npm link for source packages
        for pkg_name, (pkg, node_data) in self._source_pkgs.items():
            if node_data.link and hasattr(pkg, "path") and pkg.path:
                with self.task_context(update_info, "node-link-%s" % pkg_name,
                                       "Linking %s" % pkg_name):
                    self._run_link(manager, pkg.path, node_dir, update_info)

        # Patch packages.envrc
        emit_env = node_config.env if node_config is not None else True
        if emit_env:
            _write_node_envrc(node_dir)
            _patch_packages_envrc_node(deps_dir)

        # Warn if lockfile is gitignored
        lockfile = os.path.join(node_dir, "package-lock.json")
        if manager == "npm" and os.path.isfile(lockfile) and _is_gitignored(lockfile):
            note("WARNING: packages/node/package-lock.json is gitignored. "
                 "Consider committing it for reproducible builds.")

    def _write_package_json(self, path: str):
        """Synthesise packages/node/package.json from collected packages."""
        deps = {}
        dev_deps = {}
        for name, pkg in self._npm_pkgs.items():
            if pkg.dev:
                dev_deps[name] = pkg.version
            else:
                deps[name] = pkg.version

        data = {
            "name": "ivpm-node-env",
            "version": "1.0.0",
            "private": True,
        }
        if deps:
            data["dependencies"] = deps
        if dev_deps:
            data["devDependencies"] = dev_deps

        with open(path, "w") as fp:
            json.dump(data, fp, indent=2)
            fp.write("\n")

    def _run_install(self, manager: str, node_dir: str, update_info: ProjectUpdateInfo):
        """Run the appropriate package manager install command."""
        suppress = getattr(update_info, "suppress_output", False)
        if manager == "npm":
            cmd = ["npm", "install", "--prefix", node_dir]
        elif manager == "pnpm":
            cmd = ["pnpm", "install", "--dir", node_dir]
        elif manager == "yarn":
            cmd = ["yarn", "install", "--cwd", node_dir]
        else:
            fatal("Unknown node package manager: %s" % manager)

        _logger.info("Running: %s", " ".join(cmd))
        kwargs = {}
        if suppress:
            kwargs["stdout"] = subprocess.DEVNULL
            kwargs["stderr"] = subprocess.DEVNULL
        try:
            subprocess.run(cmd, check=True, **kwargs)
        except subprocess.CalledProcessError as e:
            fatal("Node package install failed (exit %d): %s" % (e.returncode, " ".join(cmd)))
        except FileNotFoundError:
            fatal("'%s' not found — please install Node.js and %s" % (manager, manager))

    def _run_link(self, manager: str, pkg_path: str, node_dir: str, update_info: ProjectUpdateInfo):
        """npm link a source package into the node environment."""
        suppress = getattr(update_info, "suppress_output", False)
        if manager == "npm":
            cmd = ["npm", "link", pkg_path, "--prefix", node_dir]
        elif manager == "pnpm":
            cmd = ["pnpm", "link", pkg_path, "--dir", node_dir]
        elif manager == "yarn":
            cmd = ["yarn", "link", "--cwd", node_dir, pkg_path]
        else:
            return

        _logger.info("Running: %s", " ".join(cmd))
        kwargs = {}
        if suppress:
            kwargs["stdout"] = subprocess.DEVNULL
            kwargs["stderr"] = subprocess.DEVNULL
        try:
            subprocess.run(cmd, check=True, **kwargs)
        except subprocess.CalledProcessError as e:
            _logger.warning("npm link failed for '%s' (exit %d)", pkg_path, e.returncode)
        except FileNotFoundError:
            _logger.warning("'%s' not found — cannot link '%s'", manager, pkg_path)

    # ------------------------------------------------------------------
    # State persistence
    # ------------------------------------------------------------------

    def get_state_entries(self) -> dict:
        installed = list(self._npm_pkgs.keys()) + list(self._source_pkgs.keys())
        return {
            "manager": "npm",
            "installed": sorted(installed),
            "package_json_hash": self._current_pkg_json_hash,
        }
